/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.garesst.gmost.vistas;

import com.garesst.gmost.main;
import com.garesst.gmost.modelos.conexion;
import com.garesst.gmost.recursos.BaseDatos;
import com.garesst.gmost.recursos.Conexion;
import com.garesst.gmost.recursos.RecursoConector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author oscar
 */
public class frmConexion extends javax.swing.JFrame {

    /**
     * Creates new form frmConexion
     */
    public frmConexion() {
        initComponents();
        cbbRecurso.setModel(new DefaultComboBoxModel(RecursoConector.values()));
        cbbBaseDatos.setModel(new DefaultComboBoxModel(BaseDatos.values()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTest = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblRecurso = new javax.swing.JLabel();
        cbbRecurso = new javax.swing.JComboBox<>();
        cbbBaseDatos = new javax.swing.JComboBox<>();
        lblBaseDatos = new javax.swing.JLabel();
        lblRecurso1 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblPuerto = new javax.swing.JLabel();
        txtPuerto = new javax.swing.JSpinner();
        lblPassword1 = new javax.swing.JLabel();
        btnConectar = new javax.swing.JButton();
        cbbBasesdeDatos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTest.setText("Probar Conexión");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Ubuntu", 3, 36)); // NOI18N
        lblTitulo.setText("Gestor de Conexiones");

        lblRecurso.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblRecurso.setText("Recurso");

        lblBaseDatos.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblBaseDatos.setText("Base de Datos");

        lblRecurso1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblRecurso1.setText("URL");

        lblUser.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblUser.setText("Usuario");

        lblPassword.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPassword.setText("Contraseña");

        lblPuerto.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPuerto.setText("Puerto");

        txtPuerto.setModel(new javax.swing.SpinnerNumberModel(3306, null, null, 1));
        txtPuerto.setToolTipText("");

        lblPassword1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblPassword1.setText("Base de Datos");

        btnConectar.setText("Conectar");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });

        cbbBasesdeDatos.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRecurso)
                    .addComponent(lblRecurso1)
                    .addComponent(lblUser)
                    .addComponent(lblPuerto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUrl)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbbRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblBaseDatos)
                        .addGap(18, 18, 18)
                        .addComponent(cbbBaseDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPassword))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPassword1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbBasesdeDatos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPassword))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnTest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRecurso)
                    .addComponent(cbbRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBaseDatos)
                    .addComponent(cbbBaseDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRecurso1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword)
                    .addComponent(lblUser)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword1)
                    .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPuerto)
                    .addComponent(cbbBasesdeDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTest)
                    .addComponent(btnConectar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
        conexion objetConexion = new conexion(null, (RecursoConector)cbbRecurso.getSelectedItem(), (BaseDatos)cbbBaseDatos.getSelectedItem(), "", txtUrl.getText(), txtPuerto.getValue().toString(), txtUser.getText(), txtPassword.getText());
        Conexion ctrlConexion = new Conexion();
        objetConexion.setConn(ctrlConexion.getConn(objetConexion));
        if(objetConexion.getConn() != null){
            btnConectar.setEnabled(true);
            cbbBasesdeDatos.setModel(new DefaultComboBoxModel(ctrlConexion.obtenerBasesDatos(objetConexion.getConn()).toArray()));
            cbbBasesdeDatos.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "La conexion fue exitosa");
        }else{
            btnConectar.setEnabled(false);
            cbbBasesdeDatos.setModel(null);
            cbbBasesdeDatos.setEnabled(false);
            JOptionPane.showMessageDialog(rootPane, "La conexion no tuvo exito");
        }
    }//GEN-LAST:event_btnTestActionPerformed

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
        String BasedeDatos = cbbBasesdeDatos.getSelectedIndex()==0?"":cbbBasesdeDatos.getSelectedItem().toString();
        conexion objetConexion = new conexion(null, (RecursoConector)cbbRecurso.getSelectedItem(), (BaseDatos)cbbBaseDatos.getSelectedItem(), BasedeDatos, txtUrl.getText(), txtPuerto.getValue().toString(), txtUser.getText(), txtPassword.getText());
        Conexion ctrlConexion = new Conexion();
        objetConexion.setConn(ctrlConexion.getConn(objetConexion));
        if(objetConexion.getConn() == null){
            JOptionPane.showMessageDialog(rootPane, "La conexion no tuvo exito");
        }else{
            main.variablesAplicacion.setRecursoConexion(ctrlConexion);
            main.variablesAplicacion.setRecursoLogin(Boolean.TRUE);
            main.variablesAplicacion.setRecursoModelConexion(objetConexion);
            ctrlConexion = null;
            objetConexion = null;
            frmInicio frm = new frmInicio(this, Boolean.TRUE);
            this.setVisible(Boolean.FALSE);
            frm.setVisible(Boolean.TRUE);
        }
    }//GEN-LAST:event_btnConectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmConexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnTest;
    private javax.swing.JComboBox<String> cbbBaseDatos;
    private javax.swing.JComboBox<String> cbbBasesdeDatos;
    private javax.swing.JComboBox<String> cbbRecurso;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBaseDatos;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblPuerto;
    private javax.swing.JLabel lblRecurso;
    private javax.swing.JLabel lblRecurso1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JSpinner txtPuerto;
    private javax.swing.JTextField txtUrl;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
